# version for 'time'
sudo: false
language: perl6
perl6:
    - latest

install:
    - rakudobrew build-zef
    # the following command avoids double-testing of the target module:
    - git clone https://github.com/tbrowder/PERL6LIB.git
    - zef install PERL6LIB
    - zef install --depsonly .
